<?php

namespace app\controllers\api;

use app\forms\CardForm;
use app\services\ProductService;
use yii\filters\VerbFilter;

class ProductController extends BaseApiController
{
    private ProductService $service;
    public function behaviors(): array
    {
        return [
            [
                'class' => VerbFilter::class,
                'actions' => [
                    'product-type' => ['POST'],
                ],
            ]
        ];
    }

    public function init(): void
    {
        $this->service = new ProductService();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionProductType(): array
    {
        $productTypeForm = new CardForm();
        $productTypeForm->load($this->request->post());
        if ($productTypeForm->validate()) {
            $this->service->createProductCard($productTypeForm);
            $this->jsonApi->setupCode(204);
            return [];
        }
        return $this->jsonApi->addModelErrors($productTypeForm)->asArray();
    }
}