<?php

namespace app\controllers\api;

use app\domain\ManageProductType\UseCases\ProductService;
use app\forms\ParsingSchemaForm;
use app\forms\ProductTypeForm;
use yii\filters\VerbFilter;

class ProductController extends BaseApiController
{
    private ProductService $service;
    public function behaviors(): array
    {
        return array_merge(parent::behaviors(), [
            [
                'class' => VerbFilter::class,
                'actions' => [
                    'product-type' => ['post'],
                ],
            ]
        ]);
    }

    public function init(): void
    {
        $this->service = new ProductService();
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionCreateType(): array
    {
        $productTypeForm = new ProductTypeForm();
        $productTypeForm->load($this->request->post());
        if ($productTypeForm->validate()) {
            $id = $this->service->createProductType($productTypeForm);
            $this->jsonApi->addField('id', $id);
            $this->jsonApi->setupCode(200);
            return $this->jsonApi->asArray();
        }
        return $this->jsonApi->addModelErrors($productTypeForm)->asArray();
    }

    public function actionCreateSchema(): array{
        $schemaForm = new ParsingSchemaForm();
        $schemaForm->load($this->request->post());
        if($schemaForm->validate()){
            return $this->jsonApi->asArray();
        }
        return $this->jsonApi
            ->addModelErrors($schemaForm)
            ->asArray();
    }
}