<?php

namespace app\modules\ProductTableSettings;

use yii\base\Module;

class ProductTableSettingsModule extends Module
{
    public function runAction($route, $params = [])
    {
        return parent::runAction($route, $params); // TODO: Change the autogenerated stub
    }
}