version: '3.2'

services:
  reverse-proxy:
    image: 'jwilder/nginx-proxy'
    container_name: 'reverse-proxy-pricecheck'
    ports:
      - '${PORT}:80'
    volumes:
      - './proxy/vhosts:/etc/nginx/vhost.d'
      - './proxy/config:/etc/nginx/conf.d'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './proxy/certs:/etc/nginx/certs'
    networks:
      - pricecheck


  # прокси для пхп
  php-proxy:
    image: nginx
    container_name: "php-proxy-pricecheck"
    volumes:
      - './php/proxy:/etc/nginx/conf.d'
    environment:
      VIRTUAL_HOST: "${BACKEND}"
    links:
      - php
    volumes_from:
      - php
    networks:
      - pricecheck

  postgres:
    image: postgres:latest
    container_name: "pg-pricecheck"
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./pg/data:/data/db
    networks:
      - pricecheck

  php:
    container_name: "php-pricecheck"
    build:
      context: ./php/
    volumes:
      - '../backend:/var/www/html'
    environment:
      EXTERNAL_IP: "${EXTERNAL_IP}"
      PHP_IDE_CONFIG: 'serverName=${SERVER_NAME}'
    networks:
      - pricecheck

  ### тут происходит подгрузка зависимостей для бека и фронта
  php-cli:
    container_name: "php-cli-pricecheck"
    build:
      context: ./php/
    volumes:
      - "../backend:/var/www/html"
    command: bash -c  "${BACKEND_DEPLOY_SCRIPT}"
    depends_on:
      - postgres
    networks:
      - pricecheck

  ## статика панели пользователя
#  nginx-user-panel:
#    image: nginx
#    container_name: "nginx-user-panel"
#    volumes:
#      - './nuxt/proxy/panel:/etc/nginx/conf.d'
#    environment:
#      VIRTUAL_HOST: "${USER_PANEL}"
#    links:
#      - user-panel
#    volumes_from:
#      - user-panel
#
#  user-panel:
#    container_name: "user-panel"
#    image: node:latest
#    working_dir: "/app"
#    environment:
#      NODE_OPTIONS: --openssl-legacy-provider
#      HOST: 0.0.0.0
#      PORT: 4001
#      CHOKIDAR_USEPOLLING: 1
#    volumes:
#      - '../frontend.user.panel:/app'
#    ports:
#      - "4001:4001"
#    command: bash -c  "${FRONTEND_DEPLOY_SCRIPT}"

  ## статика
  nginx-admin-panel:
    image: nginx
    container_name: "nginx-admin-panel"
    volumes:
      - './nuxt/proxy/admin:/etc/nginx/conf.d'
    environment:
      VIRTUAL_HOST: "${ADMIN_PANEL}"
    links:
      - admin-panel
    volumes_from:
      - admin-panel
    networks:
      - pricecheck

  admin-panel:
    container_name: "admin-panel"
    image: node:latest
    working_dir: "/app"
    environment:
      NODE_OPTIONS: --openssl-legacy-provider
      HOST: 0.0.0.0
      PORT: 4000
      CHOKIDAR_USEPOLLING: 1
    volumes:
      - '../admin:/app'
    ports:
      - "4000:4000"
    command: bash -c  "${FRONTEND_DEPLOY_SCRIPT}"
#    command: bash -c  "npm start"
    networks:
      - pricecheck

networks:
  pricecheck:
    name: "pricecheck"