version: '3.2'

services:
  reverse-proxy:
    image: 'jwilder/nginx-proxy'
    container_name: 'reverse-proxy-pricecheck'
    ports:
      - '${PORT}:80'
    volumes:
      - './proxy/vhosts:/etc/nginx/vhost.d'
      - './proxy/config:/etc/nginx/conf.d'
      - '/var/run/docker.sock:/tmp/docker.sock:ro'
      - './proxy/certs:/etc/nginx/certs'


  # прокси для пхп
  php-proxy:
    image: nginx
    container_name: "php-proxy-pricecheck"
    volumes:
      - './php/proxy:/etc/nginx/conf.d'
    environment:
      VIRTUAL_HOST: "${BACKEND}"
    links:
      - php
    volumes_from:
      - php

  mongo:
    image: mongo:latest
    env_file:
      - .env
    volumes:
      - ./mongo/data:/data/db
    ports:
      - "27017:27017"

  mongoClientTemp:
    image: mongo:latest
    container_name: mongoClientTemp
    links:
      - mongo:mongo
    command: mongo --host mongo --eval  "db.getSiblingDB('dashboard').createUser({user:'db', pwd:'dbpass', roles:[{role:'readWrite',db:'dashboard'}]});"
    depends_on:
      - mongo

  php:
    container_name: "php-pricecheck"
    build:
      context: ./php/
    volumes:
      - '../src:/var/www/html'
    environment:
      EXTERNAL_IP: "${EXTERNAL_IP}"
      PHP_IDE_CONFIG: 'serverName=${SERVER_NAME}'

  mysql:
    image: mysql:8.0
    container_name: "mysql-pricecheck"
    env_file:
      - .env
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    command: [
      'mysqld',
      '--character-set-server=utf8mb4',
      '--collation-server=utf8mb4_unicode_ci'
    ]

  ### тут происходит подгрузка зависимостей для бека и фронта
  php-cli:
    container_name: "php-cli-pricecheck"
    build:
      context: ./php/
    volumes:
      - "../src:/var/www/html"
    command: bash -c  "${BACKEND_DEPLOY_SCRIPT}"
    depends_on:
      - mysql