<?php

namespace app\forms;


use elisdn\compositeForm\CompositeForm;

/**
 * @property ProductFieldForm[] $fields
 */
class ProductForm extends CompositeForm
{
    public $name;

    public function init(): void
    {
        $this->fields = [];
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function rules(): array
    {
        return [
            ['name', 'required'],
        ];
    }

    protected function internalForms(): array
    {
        return ['fields'];
    }

    public function formName(): string
    {
        return '';
    }
}